/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, BlogPost as PrismaBlogPost } from "@prisma/client";

export class BlogPostServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.BlogPostCountArgs, "select">): Promise<number> {
    return this.prisma.blogPost.count(args);
  }

  async blogPosts<T extends Prisma.BlogPostFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.BlogPostFindManyArgs>
  ): Promise<PrismaBlogPost[]> {
    return this.prisma.blogPost.findMany<Prisma.BlogPostFindManyArgs>(args);
  }
  async blogPost<T extends Prisma.BlogPostFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.BlogPostFindUniqueArgs>
  ): Promise<PrismaBlogPost | null> {
    return this.prisma.blogPost.findUnique(args);
  }
  async createBlogPost<T extends Prisma.BlogPostCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.BlogPostCreateArgs>
  ): Promise<PrismaBlogPost> {
    return this.prisma.blogPost.create<T>(args);
  }
  async updateBlogPost<T extends Prisma.BlogPostUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.BlogPostUpdateArgs>
  ): Promise<PrismaBlogPost> {
    return this.prisma.blogPost.update<T>(args);
  }
  async deleteBlogPost<T extends Prisma.BlogPostDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.BlogPostDeleteArgs>
  ): Promise<PrismaBlogPost> {
    return this.prisma.blogPost.delete(args);
  }
}
